# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
os: linux
r_packages:
- pkgdown
cache: packages
- Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip_cleanup: true
  token: "$GITHUB_PAT"
  keep_history: true
  local_dir: docs
  on:
    branch: master
